url: "http://manu183.github.io/SmubiIDWeb/"
baseurl: "/"

# Site settings
title: Smubi ID
email: manuellang183@gmail.com
description: "We are Smubi ID, a young group of students at KIT Karlsruhe Germany working on AR solution with Unity and HoloLens. Team Smubi participating at KPMG Ideation Challenge and won the world final in Amsterdam, Netherlands."

plugins:
  - jekyll-seo-tag

# Team names, titles and social links
people:
- name: Christoph<br/> Bamberger
  pic: 1
  position: Sales
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/christoph-bamberger-84367a131/

- name: Sebastian<br/> Findeisen
  pic: 2
  position: Finance
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sebastian-findeisen-56004685/

- name: Tristan<br/> Karb
  pic: 3
  position: Operations
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/tristan-karb-262134151/

- name: Manuel<br/> Lang
  pic: 4
  position: Development
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/manuel-lang/

- name: Minh-Kha<br/> Nguyen
  pic: 5
  position: User Experience
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/minh-kha-nguyen-955980112/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty